"use client";

import React from "react";
import { useRouter } from "next/navigation";

export default function PrivacyPolicyPage() {
  const router = useRouter();

  return (
    <div style={{ background: "#0f172a", minHeight: "100vh", color: "#ffffff", fontFamily: "Arial, sans-serif", paddingBottom: "6px" }}>
      {/* HEADER */}
      <header style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "15px 30px", borderBottom: "1px solid #1e293b", background: "#1e293b" }}>
        <span style={{ fontSize: "17px", fontWeight: "900", color: "#34d399", letterSpacing: "1px" }}>🔒 DATA PRIVACY CHARTER</span>
        <button onClick={() => router.push("/")} style={{ background: "transparent", border: "1px solid #34d399", color: "#34d399", padding: "8px 16px", borderRadius: "6px", cursor: "pointer", fontSize: "13px", fontWeight: "bold" }}>
          ⬅️ Return Home
        </button>
      </header>

      {/* CORE FRAMEWORK PANEL */}
      <div style={{ maxWidth: "800px", margin: "40px auto", background: "#1e293b", padding: "40px", borderRadius: "16px", border: "1px solid #334155", lineHeight: "1.6" }}>
        <h1 style={{ color: "#ffffff", marginBottom: "4px" }}>Data Protection & Privacy Policy</h1>
        <p style={{ color: "#94a3b8", fontSize: "14px", marginBottom: "30px" }}>Effective Date: July 2026 | KiKa Global Services Limited, Kampala, Uganda</p>

        <div style={{ background: "rgba(52, 211, 153, 0.05)", border: "1px solid #334155", padding: "15px", borderRadius: "8px", color: "#34d399", fontSize: "13px", marginBottom: "25px" }}>
          💡 <strong>Statutory Regulatory Notice:</strong> This charter is compiled to achieve absolute compliance with the Uganda Data Protection and Privacy Act, 2019. KiKa Global Services Limited is registered with the Personal Data Protection Office (PDPO) under NITA-U as a certified Data Controller and Processor.
        </div>

        <h3 style={sectionHeaderStyle}>1. Information We Collect Matrix</h3>
        <p style={paragraphStyle}>To authorize secure cross-border intermediation and statutory ledger tracking, KiKa collects the following metrics via your Next.js application frontend:</p>
        <ul style={listStyle}>
          <li><strong>Identity Records:</strong> Full Legal Name, Date of Birth, Biological Sex classification, and Marital Status indexes.</li>
          <li><strong>Compliance Identity Metrics:</strong> Ugandan Passport Serial Numbers and National Identification Numbers (NIN) to fulfill international Anti-Money Laundering (AML) and KYC thresholds.</li>
          <li><strong>Spatial Geolocation Tracking:</strong> Host Country of residence, physical domicile address, and structural GPS location coordinates.</li>
          <li><strong>Financial Metadata:</strong> Wallet balance allocations, transaction reference IDs generated by clearing networks (Paystack/Flutterwave), and Sacco structural ledger metrics. <em>KiKa never caches or stores raw credit card details or Mobile Money PIN parameters on our local servers.</em></li>
        </ul>

        <h3 style={sectionHeaderStyle}>2. Cryptographic Security Standards</h3>
        <p style={paragraphStyle}>Your access credentials and profile states are protected by industry-leading security mechanisms. Passwords inputted via our interface components are dynamically processed using an asynchronous, salted cryptographic key derivation algorithm (Node.js <code>crypto.scrypt</code>) before being committed to our PostgreSQL cluster. This ensures your account keys remain un-crackable even in local development or staging environments run over exposed proxy tunnels like ngrok.</p>

        <h3 style={sectionHeaderStyle}>3. Data Sharing & Trans-Border Disclosures</h3>
        <p style={paragraphStyle}>KiKa protects user confidentiality. Your transactional data pools are exclusively shared with licensed aggregators (Paystack, Flutterwave) and registered cooperative SACCO institutions that you programmatically authorize. In full accordance with Section 32 of the Uganda Data Protection Act, no customer telemetry or identification indices are transferred outside the sovereign tracking parameters of Uganda unless encrypted end-to-end to protect the user's data sovereignty.</p>

        <h3 style={sectionHeaderStyle}>4. Your Legal Rights under PDPO</h3>
        <p style={paragraphStyle}>Ugandan citizens and members of the global diaspora retain the structural right to request access to their digital ledger trail, demand correction of faulty identity metrics, or request absolute deletion of their login nodes. For data privacy inquiries or compliance auditing, reach out directly to our Data Protection Hub at <strong>privacy@kikaglobal.com</strong>.</p>
      </div>
    </div>
  );
}

const sectionHeaderStyle = { color: "#34d399", fontSize: "16px", marginTop: "25px", borderBottom: "1px solid #334155", paddingBottom: "4px", textTransform: "uppercase" as const, letterSpacing: "0.5px" };
const paragraphStyle = { color: "#cbd5e1", fontSize: "14px", margin: "10px 0" };
const listStyle = { color: "#cbd5e1", fontSize: "14px", paddingLeft: "20px" };
